CREATE TABLE MessageData (ID INTEGER IDENTITY(1,1) PRIMARY KEY, Author VARCHAR(16), Recipient VARCHAR(16), TimeSent VARCHAR(19) DEFAULT CONVERT(VARCHAR, CURRENT_TIMESTAMP), Content VARCHAR(64));
CREATE TABLE Notifications (ID INTEGER IDENTITY(1,1) PRIMARY KEY, Originator VARCHAR(16), TimeSent VARCHAR(19) DEFAULT CONVERT(VARCHAR, CURRENT_TIMESTAMP), Content VARCHAR(64));

INSERT INTO MessageData VALUES('Elliott', 'Myself', DEFAULT, 'TestMessage');
INSERT INTO MessageData VALUES('Elliott', 'Myself', DEFAULT, 'Hello World!');

SELECT * FROM MessageData